preload = /home/kamusari/wallpapers/Kurumi-Ebisuzawa.png
preload = /home/kamusari/wallpapers/this-wallpaper-is-not-available.png
wallpaper = DP-1, /home/kamusari/wallpapers/Kurumi-Ebisuzawa.png
wallpaper = HDMI-A-1, /home/kamusari/wallpapers/this-wallpaper-is-not-available.png
