# ╻ ╻╻┏┓╻╺┳┓┏━┓╻ ╻┏━┓   ┏━┓┏┓╻╺┳┓   ╻ ╻┏━┓┏━┓╻┏ ┏━┓┏━┓┏━┓┏━╸┏━╸┏━┓
# ┃╻┃┃┃┗┫ ┃┃┃ ┃┃╻┃┗━┓   ┣━┫┃┗┫ ┃┃   ┃╻┃┃ ┃┣┳┛┣┻┓┗━┓┣━┛┣━┫┃  ┣╸ ┗━┓
# ┗┻┛╹╹ ╹╺┻┛┗━┛┗┻┛┗━┛   ╹ ╹╹ ╹╺┻┛   ┗┻┛┗━┛╹┗╸╹ ╹┗━┛╹  ╹ ╹┗━╸┗━╸┗━┛

# hyprctl clients - узнать класс приложения

workspace = 5, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 1, monitor:DP-1
workspace = 6, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

# Chrome
windowrulev2 = workspace 1, class:(google-chrome)$

# Prism Launcher
windowrulev2 = workspace 3, class:(PrismLauncher)$

windowrulev2 = float, class:(PrismLauncher)$, title:(Prism Launcher 9.2)$
windowrulev2 = size 770 620, class:(PrismLauncher)$, title:(Prism Launcher 9.2)$
windowrulev2 = center, class:(PrismLauncher)$, title:(Prism Launcher 9.2)$
windowrulev2 = move, 887 200, class:(PrismLauncher)$, title:(Prism Launcher 9.2)$

windowrulev2 = float, class:(PrismLauncher)$, title:(Console window)$
windowrulev2 = size 770 620, class:(PrismLauncher)$, title:(Console window)$
windowrulev2 = center, class:(PrismLauncher)$, title:(Console window)$
windowrulev2 = move, 105 200, class:(PrismLauncher)$, title:(Console window)$

#GTNH
windowrulev2 = workspace 4, class:(GT: New Horizons 2.7.3)$
windowrulev2 = fullscreenstate:* 1, class:(GT: New Horizons 2.7.3)$

# Telegram
windowrulev2 = workspace 5 silent, class:(TelegramDesktop)$
windowrulev2 = float, class:(TelegramDesktop)$, title:(Media viewer)$
windowrulev2 = size, 800 600, class:(TelegramDesktop)$ title:(Media viewer)$

windowrulev2 = size 970 480, class:(TelegramDesktop)$, title:(Choose Files)$
windowrulev2 = center, class:(TelegramDesktop)$, title:(Choose Files)$

windowrulev2 = size 970 480, class:(TelegramDesktop)$, title:(Save File)$
windowrulev2 = center, class:(TelegramDesktop)$, title:(Save File)$

# Vesktop
windowrulev2 = workspace 10 silent, class:(vesktop)$
windowrulev2 = float, class:(vesktop)$, title:(Open Files)$
windowrulev2 = size 1160 630, class:(vesktop)$, title:(Open Files)$
windowrulev2 = center, class:(vesktop)$, title:(Open Files)$

# AmneziaVPN
windowrulev2 = workspace 10 silent, title:(AmneziaVPN)$
windowrulev2 = float, title:(AmneziaVPN)$

# Pavucontrol
windowrulev2 = float, class:(org.pulseaudio.pavucontrol)$
windowrulev2 = center, class:(org.pulseaudio.pavucontrol)$
windowrulev2 = size 1160 630, class:(org.pulseaudio.pavucontrol)$

# QT5CT/QT6CT
windowrulev2 = float, class:(qt.*ct)$
windowrulev2 = center, class:(qt.*ct)$

blurls = waybar
blurls = rofi

layerrule = blur,logout
layerrule = xray 0, notifications
layerrule = animation slide, notifications
